language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
  - "pypy"
  - "pypy3"

install:
  - pip install -e .[test] git+https://github.com/realraum/r3py.git

script:
  - echo $TRAVIS_PYTHON_VERSION
  - py.test

notifications:
    email: false

matrix:
  fast_finish: true
